#!/bin/sh

RED="\e[31m"
GREEN="\e[32m"

if ! head -1 "$1" | grep -qE "^(feat|fix|chore|docs|test|style|refactor|perf|build|ci|revert)(\(.+?\))?: .{1,}$"; then
    echo -e "${RED}Aborting commit. Your commit message is invalid.${ENDCOLOR}" >&2
    echo -e "${RED}See docs for more info -> https://www.conventionalcommits.org/en/v1.0.0/${ENDCOLOR}" >&2
    exit 1
fi
if ! head -1 "$1" | grep -qE "^.{1,88}$"; then
    echo -e "${RED}Aborting commit. Your commit message is invalid.${ENDCOLOR}" >&2
    echo -e "${RED}See docs for more info -> https://www.conventionalcommits.org/en/v1.0.0/${ENDCOLOR}" >&2
    exit 1
fi

echo "Commit is valid."